add_newline = false
format = """
$directory\
${custom.aws_profile_serverless}\
${custom.aws_profile_administrator}\
${custom.aws_profile_systemadministrator}\
${custom.aws_stage}\
$cmd_duration\
$character
"""

[character]
success_symbol = "[❱](dimmed cyan)"
error_symbol = "[❱](dimmed red)"
vicmd_symbol = "[❱](cyan)"

[directory]
truncate_to_repo = true
truncation_length = 10

[custom.aws_profile_serverless]
shell = "dash"
command = "echo $travelstop_prompt_aws_profile"
when = "test \"$travelstop_prompt_aws_profile\" = ServerlessDeployNonProd"
format = "[$output](bold yellow)"

[custom.aws_profile_administrator]
shell = "dash"
command = "echo $travelstop_prompt_aws_profile"
when = "test \"$travelstop_prompt_aws_profile\" = AdministratorNonProd"
format = "[$output](bold underline green)"

[custom.aws_profile_systemadministrator]
shell = "dash"
command = "echo $travelstop_prompt_aws_profile"
when = "test \"$travelstop_prompt_aws_profile\" = SystemAdministratorNonProd"
format = "[$output](bold green)"

[custom.aws_stage]
shell = "dash"
command = "echo $travelstop_prompt_aws_stage"
when = "true"
format = " [$output](bold purple) "
